### ISSUE TITLE
Incorrect warning about dictionary return type with strict type check enabled

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/monkeyc-optimizer#30] opened 2024-04-17 22:41 UTC
```monkey-c
function test() as { :x as Number? } {
    // Expected $.Test.test to return { :x as Null or Number } but got { :x as Null or Object }
    return { :x => null };
}
```
With `return { :x => null as Number? };` result is the same.

**Comment by m4tiz5zktonj** [comment] 2024-04-17 23:01
Probably, the same issue. Again, only with strict type check enabled.
```monkey-c
function test2(value as Boolean) as Array<Array<Number>> {
    var array = [[0] as Array<Number>] as Array<Array<Number>>;

    var element = value ? [0] as Array<Number> : null;

    if (value) {
        // Invalid assignment to array[0]. Expected Array<Number> but got Null or Array<Number> [pmc-analysis]
        array[0] = element;
    }

    // Expected $.Test.test2 to return Array<Array<Number>> but got Array<Null or Array<Number>> [pmc-analysis]
    return array;
}
```

**Comment by markw65** [comment] 2024-04-18 01:00
The second example doesn't seem to be related to the first in any way. Also, the second example isn't very compelling.

You're complaining that my type checker doesn't realize that since the test is the same in both cases, element is guaranteed to be non null inside the if.

But Garmin's type checker doesn't do that either. It's just that Garmin's type checker doesn't care in this case, and is happy to assign an `Array<Number> or Null` to `array[0]`. In fact if you reverse one of the tests (so that element is guaranteed to be null inside the if), Garmin's compiler doesn't complain either.

So that second case is a won't-fix. My type checker is doing better than Garmin's.

**Comment by m4tiz5zktonj** [comment] 2024-04-18 07:21
> You're complaining that my type checker doesn't realize that since the test is the same in both cases, element is guaranteed to be non null inside the if.

Yes, for some reason I was expecting that. But also I know that it is not a trivial case. I completely understand that and definitely can live with it.

Thanks for your work!

**Comment by markw65** [comment] 2024-04-18 13:08
> Yes, for some reason I was expecting that

It would be nice to handle, but this one isn't something that most type checkers try to deal with. eg [here's the corresponding example in typescript](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUA3AhgGxAUwC4AjVHfLMASkQG8AoRJxCBAZykSwCdvDEwIALbF83ANoBdRAF5E4gIwAaAExKAzJIDc9Rs2zdE+WYmx5jAfkQAWFYn6CcOHc0QxgiTLgI0Gr1zwSCtJy+C7MAL70EUA)

And more significantly Garmin's type checker doesn't handle it; so if mine did it would tell you your code was ok, and then Garmin would refuse to compile it. This example only "works" because for some reason Garmin allows you to assign an `Array<Number> or Null` to an element of an `Array<Array<Number>>` - even though it would not allow you to assign a `Number or Null` to an `Array<Number>`

**Comment by markw65** [comment] 2024-12-09 20:19
The problem is the same in both cases.

After

```
var x = [null];
```

What is x's inferred type? If it's `[Null]` then a subsequent `x[0] = 42` is an error, because it doesn't match the type. So I widen `null` to `Object?`. But then we end up with this problem.

I'm not sure what the correct fix is. If I ever do the escape analysis I was talking about on another issue, I can relax the assignment checks for tuples. Basically if you're assigning to a tuple that you own 100%, there's no need to restrict the assignment. You can assign what you like, and the type just updates.

But that has some odd side effects:
```
var x = [null];
var y = [null];
var z = y; // or foo(y) etc. Something that "leaks" the value.

x[0] = 42; // ok, x is the only reference to its array
y[0] = 42; // error, there are other references to y's array
```

**Comment by markw65** [comment] 2024-12-12 17:56
I'm also thinking along these lines as a "stop gap" solution.

> could the null as Something? be typed as Something? instead of Object??

The problem here is that generally, if the optimizer finds a cast that strictly widens the type, then it drops the cast. So `null as Number?` is converted to `null`.

I generally try to avoid taking "context" into account in the optimizer; the optimizations performed on an expression `E` should depend only on `E` and not on where `E` occurs. Or at least, if there's an optimization that can only be done if `E` occurs as a subexpression of something else, I still optimize `E` first, and then do the later optimizations.

In this case, that means I first see `null as Number?`, and optimize it, and then by the time I look at the tuple, I've already removed the cast.

So `[null] as [Number?]` works, but `[null as Number?]` currently does not. Of course, in more complex cases, this isn't as nice. You would have to say `[42, "foo", 24.0, null] as [Number, String, Float, Number?]`, where the first three types were already correctly deduced by the compiler.

But I think in this case, I can treat the cast as belonging to the `ArrayExpression` (or `ObjectExpression`), and hang onto it.

**Comment by markw65** [comment] 2024-12-12 18:50
Btw, sorry this is taking so long, I'm just not getting much time to work on this these days.

Also, to explain what I'm going for here, the goal is that you shouldn't be able to change the type of a possibly-shared tuple without a warning, or an explicit cast. This means I have to warn about a lot of cases that Garmin doesn't - and sometimes, these warnings are not relevant.

But Garmin thinks this is fine, for example:
```
function foo() as [Number] {
    var x = [42];
    var y = x;
    // Garmin allows you to change the type of the tuple, which seems reasonable;
    // the types of local variables are always inferred, and this is a local. The problem
    // is that the thing referred to by this local could be shared (and is).
    x[0] = "Hello";
    // Garmin thinks this is ok, because y's type was [Number] when it was initialized,
    // and y hasn't been modified.
    return y;
}
```

Until I get around to doing a reasonable level of escape analysis, there are always going to be "obviously" incorrect warnings though:

```
function foo() as [String] {
    var x = [42];
    // I still warn here, even though this time it's fine
    x[0] = "Hello";
    return x;
}
```

**Closed** 2024-12-15 23:28 UTC
